"""Emit paper Table 2: trained MPS-V tensor-network scaling on the orthogonal GMM.

Trained-V 2TDVP scaling runs at MPS-V D=8, sigma=0.5, fixed K=160, for d in
{8, 12, 16, 32}. Columns: dimension d; oracle parameter count; endpoint
sliced-Wasserstein SW^wf_T (mean +/- 95% CI over n=10 MPS-V initialisations);
the classical action-matching floor SW^cl_T; and the achieved bond range chi*.

Inputs (both ship in the data archive, not in this repository):
  data/timing_scaling/wf_eval/mps_gaussian_mixture_d{d}_..._tdvp2_K160_.../traj.npz
      10 replicate runs per d. Only `traj.npz` is read (keys t, sw_unbiased, chi);
      the companion ck.pkl files are deliberately NOT shipped, so this repository
      carries no pickle payloads.
  data/mps_v_checkpoints/gaussian_mixture_d{d}_4modes_am_mps_orth_ts_D8_N32.pt
      the trained MPS-V oracles, for the parameter count and the classical floor.

The classical floor is recomputed here by integrating x_dot = grad V_t through the
trained oracle, so it needs torch. Whole table takes ~70 s.

The emitted LaTeX comment still reads "generated by scripts/make_scaling_table.py"
(this file's upstream name). That is deliberate: the manuscript's committed
table_scaling.tex carries that header, and changing it would break byte-for-byte
comparison against the paper.

Usage:
    make table2
    uv run python scripts/make_table2_scaling.py [--wfdir DIR] [--ckdir DIR] [--out PATH]
"""
import argparse
import os
import sys

import numpy as np
import torch

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from tnwf.data.gaussian_mixture import sample_gaussian_mixture  # noqa: E402
from tnwf.mps_v.model import MPSScalarPotentialTimeSite  # noqa: E402

WFDIR = "data/timing_scaling/wf_eval"
CKDIR = "data/mps_v_checkpoints"
OUT = "figures/table_scaling.tex"
L, SCALE, STD, NMODES = 8.0, 3.0, 0.5, 4
DIMS = [8, 12, 16, 32]                          # 2TDVP scaling, capped at d32
KIND, D_MPS, NGRID, K_FIXED = "mps", 8, 32, 160


def ckpt_name(d):
    return f"gaussian_mixture_d{d}_4modes_am_{KIND}_orth_ts_D{D_MPS}_N{NGRID}.pt"


def load_model(d):
    # The upstream version shelled out to `modal volume get` when a checkpoint was
    # absent. That is removed: this release reads only from CKDIR, so a missing
    # checkpoint is reported rather than silently fetched from private infra.
    p = f"{CKDIR}/{ckpt_name(d)}"
    if not os.path.exists(p):
        print(f"  [d{d}] missing checkpoint {p} — unpack the data archive at the "
              "repo root; the d-row will be emitted as '---'")
        return None, None
    ck = torch.load(p, map_location="cpu", weights_only=False)
    a = ck["args"]; a = a if isinstance(a, dict) else vars(a)
    m = MPSScalarPotentialTimeSite(d=d, N=int(a["N_grid"]), D=int(a["D_mps"]),
                                   L=float(a.get("L", L)), N_t=int(a.get("N_t", 16)),
                                   qtt=bool(a.get("qtt", False)))
    m.load_state_dict(ck["model"]); m.eval()
    return m, sum(p.numel() for p in m.parameters())


def classical_traj(m, d, t_eval, n=3000, sub=4, Kref=160):
    """Classical action-matching flow x_dot = grad V; return SW(t) sampled at the t_eval grid
    (the WF's logged times) so we can integrate the WF-vs-classical path deviation."""
    g = torch.Generator().manual_seed(0); xx = (L / 6.0) * torch.randn(n, d, generator=g)
    true = sample_gaussian_mixture(n, d=d, nmodes=NMODES, std=STD, scale=SCALE,
                                   arrangement="orthogonal", seed=1).astype(np.float64)
    rng = np.random.default_rng(0); u = rng.normal(size=(200, d)); u /= np.linalg.norm(u, axis=1, keepdims=True)
    sw = lambda a: float(np.mean([np.mean(np.abs(np.sort(a @ v) - np.sort(true @ v))) for v in u]))
    dt = 1.0 / (Kref * sub)
    t_eval = np.asarray(t_eval, float)
    out = np.empty_like(t_eval)
    j = 0
    sw_now = sw(xx.numpy())
    while j < len(t_eval) and t_eval[j] <= 0.0:        # any t_eval at/below 0
        out[j] = sw_now; j += 1
    for k in range(Kref):
        for s in range(sub):
            tk = (k * sub + s) * dt
            xin = xx.detach().requires_grad_(True)
            gx = torch.autograd.grad(m(xin, torch.full((n, 1), tk)).sum(), xin)[0]
            with torch.no_grad():
                xx = (xx + dt * gx).clamp(-L / 2, L / 2)
        tnow = (k + 1) / Kref
        while j < len(t_eval) and t_eval[j] <= tnow + 1e-9:
            out[j] = sw(xx.detach().numpy()); j += 1
    while j < len(t_eval):                              # any trailing points
        out[j] = sw(xx.detach().numpy()); j += 1
    return out


def wf_reps(d):
    """All completed 2TDVP rep trajectories for d (K=160): endpoint SWu, chi, flow_s.
    rep0 = suffix-free tag; rep>=1 = ..._rep{r}."""
    base = (f"{WFDIR}/mps_gaussian_mixture_d{d}_4modes_am_mps_orth_ts_D{D_MPS}_N{NGRID}"
            f"_tdvp2_K{K_FIXED}_Dmax64_M8_gt0.01_tol0.001")
    tags = [base] + [f"{base}_rep{r}" for r in range(1, 10)]
    reps = []
    for dd in tags:
        f = os.path.join(dd, "traj.npz")
        if not os.path.exists(f):
            continue
        z = np.load(f); t = np.asarray(z["t"], float)
        if t[-1] < (K_FIXED - 0.5) / K_FIXED:
            continue
        reps.append(dict(swu=float(np.asarray(z["sw_unbiased"], float)[-1]),
                         chi=int(z["chi"][-1])))
    return reps


def ci95(x):
    n = len(x)
    if n < 2:
        return float("nan")
    from scipy import stats
    return float(stats.t.ppf(0.975, n - 1) * np.std(x, ddof=1) / np.sqrt(n))


def main():
    global WFDIR, CKDIR, OUT
    p = argparse.ArgumentParser()
    p.add_argument("--wfdir", default=WFDIR)
    p.add_argument("--ckdir", default=CKDIR)
    p.add_argument("--out", default=OUT)
    args_cli = p.parse_args()
    WFDIR, CKDIR, OUT = args_cli.wfdir, args_cli.ckdir, args_cli.out

    rows = []
    for d in DIMS:
        m, npar = load_model(d)
        reps = wf_reps(d)
        n = len(reps)
        swu = [r["swu"] for r in reps]
        chis = [r["chi"] for r in reps]
        mean = float(np.mean(swu)) if n else None
        ci = ci95(swu)
        swcl = None
        if m is not None and n:
            swcl = float(classical_traj(m, d, np.linspace(0, 1, K_FIXED + 1))[-1])
        rows.append((d, npar, n, mean, ci, swcl,
                     (min(chis), max(chis)) if chis else None))
        print(f"  d{d}: n={n} SWu={mean} +/-{ci} chi={chis} SWcl={swcl}", flush=True)

    def pf(x):
        return "---" if x is None else (f"{x/1000:.0f}k" if x >= 1000 else str(x))
    def fsw(mean, ci):
        if mean is None:
            return "---"
        return f"{mean:.4f}" if ci != ci else f"{mean:.4f} $\\pm$ {ci:.4f}"
    def fcl(x):
        return "---" if x is None else f"{x:.4f}"
    def fchi(c):
        return "---" if c is None else (str(c[0]) if c[0] == c[1] else f"{c[0]}--{c[1]}")

    lines = [r"\begin{tabular}{lrrrr}", r"\toprule",
             r"$d$ & params & SW$^{\mathrm{wf}}_{T}$ (mean $\pm$ 95\% CI) & SW$^{\mathrm{cl}}_{T}$ & $\chi^\star$ \\",
             r"\midrule"]
    for d, npar, n, mean, ci, swcl, chir in rows:
        lines.append(f"{d} & {pf(npar)} & {fsw(mean, ci)} & {fcl(swcl)} & {fchi(chir)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    open(OUT, "w").write(
        "% generated by scripts/make_scaling_table.py (2TDVP, K=160, N=32; n=10 MPS-V inits; "
        "SW^wf_T = endpoint sliced-Wasserstein, mean +/- 95%% CI; "
        "SW^cl_T = classical action-matching floor; chi* = achieved-bond range)\n"
        + "\n".join(lines) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
